exclude: '.github/|docs/|requirements/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: # arguments to configure black
        - --profile=black
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      args: # arguments to configure black
        - --line-length=120
        # these folders won't be formatted by black
        - --exclude="""\.git |
          \.__pycache__|
          \**.egg-info|
          \.mypy_cache|
          \.pytest_cache|
          \.tox|
          \.venv|
          _build|
          build|
          dist"""
      language_version: python3.10
- repo: https://github.com/python-poetry/poetry
  rev: 1.2.1
  hooks:
    - id: poetry-check
      # Please activate this hook in local development environment. In Pre-Commit CI, it would occur error like below:
      # HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url ...
#    - id: poetry-lock
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
    - id: mypy
      args:
        - --config-file mypy.ini
#      package: pymock_api
#      exclude: ^test/
#      args:
##        - --strict
#        - --ignore-missing-imports
#        - --show-traceback
#      additional_dependencies: [types-PyYAML>=6.0.12.9]
