site_name: PyMock-API
#site_url: https://bryantliu.github.io/pymock-api/
site_author: Bryant Liu
site_description: >-
  Mock your APIs by YAML configuration and set up an application in minutes

# Repository
repo_name: Chisanan232/PyMock-API
repo_url: https://github.com/Chisanan232/PyMock-API

# Copyright
copyright: Copyright &copy; 2023 - 2023 Bryant Liu

theme:
  name: material
#  custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
#  favicon: assets/favicon.png
  icon:
    logo: logo

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Version requirements: getting-started/version-requirements.md
    - Installation: getting-started/installation.md
    - Configure your APIs: getting-started/configure-your-api.md
    - Set up web server: getting-started/setup-web-server.md
    - Command line usages:
      - subcommand:
        - command-line-usage/index.md
        - rest-server:
          - command-line-usage/rest-server/index.md
          - run: command-line-usage/rest-server/subcmd-run.md
          - get: command-line-usage/rest-server/subcmd-get.md
          - add: command-line-usage/rest-server/subcmd-add.md
          - check: command-line-usage/rest-server/subcmd-check.md
          - sample: command-line-usage/rest-server/subcmd-sample.md
          - pull: command-line-usage/rest-server/subcmd-pull.md
  - Configure references:
    - Basic info: configure-references/config-basic-info.md
    - Mocked API:
      - configure-references/mocked-apis/index.md
      - Template:
        - configure-references/mocked-apis/template/index.md
        - Loading setting: configure-references/mocked-apis/template/load.md
        - Values setting: configure-references/mocked-apis/template/config_path_values.md
        - Apply setting: configure-references/mocked-apis/template/apply.md
      - Base:
        - configure-references/mocked-apis/base/index.md
      - API:
        - configure-references/mocked-apis/apis/index.md
        - URL: configure-references/mocked-apis/apis/url.md
        - HTTP:
          - configure-references/mocked-apis/apis/http/index.md
          - HTTP request: configure-references/mocked-apis/apis/http/request.md
          - HTTP response: configure-references/mocked-apis/apis/http/response.md
          - Common:
            - configure-references/mocked-apis/apis/http/common/index.md
            - Item element: configure-references/mocked-apis/apis/http/common/item_element.md
  - Development:
    - development/index.md
    - How it works: development/how-it-works.md
    - Software architecture: development/software-architecture.md
    - Contributing :
      - development/contributing/index.md
      - Join in developing:
        - Developing: development/contributing/developing.md
        - Testing: development/contributing/testing.md
      - Reporting a bug: development/contributing/reporting-a-bug.md
      - Requesting a feature or change: development/contributing/requesting-a-feature.md
  - Release notes:
    - release_note/index.md
    - Version 0.X.X: release_note/version_0xx.md
