name: CI

on:
  # For the pull request event, it sniffs branch 'develop/**', 'release' and 'master' and make sure anything would be
  # fine without any issue before review and merge.
  pull_request:
    branches:
      - "dependabot/pip/**"
      - "dependabot/github_actions/actions/**"
      - "dependabot/github_actions/Chisanan232/**"

jobs:
  build-and-test:
#    name: Run all tests and organize all test reports
    uses: ./.github/workflows/rw_build_and_test.yaml
