name: documentation

on:
  push:
    branches:
      - "develop/**"
      - "master"
    paths:
      - ".github/workflows/documentation.yaml"
      - "docs/**"
      - "mkdocs.yml"

permissions:
  contents: write

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies about Poetry
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -U pip
          pip install -U poetry

      - name: Build Python runtime environment and dependencies by Poetry
        run: |
          poetry --version
          poetry install --with docs

      - name: Deploy documentation
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          poetry run mkdocs gh-deploy --force
          poetry run mkdocs --version
